version: '3'

services:

  order-api:
    build: .
    container_name: order-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data: