version: "3"

services:
  order-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: order-api
    image: aymene01/order-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: tail -f /dev/null

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
